version: 2

models:
  - name: fct_messages
    columns:
      - name: message_id
        tests:
          - not_null
          - unique
      - name: channel_id
        tests:
          - not_null

  - name: dim_channels
    columns:
      - name: channel_id
        tests:
          - unique
          - not_null